# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/modiaeventdistribution
team: oppfolging
replicas:
  min: 4
  max: 6
port: 8080
healthcheck:
  liveness:
    path: modiaeventdistribution/internal/isAlive
  readiness:
    path: modiaeventdistribution/internal/selftest
prometheus:
  enabled: true
  path: modiaeventdistribution/internal/metrics
resources:
  requests:
    cpu: 600m
    memory: 512Mi
  limits:
    cpu: 3
    memory: 1024Mi
fasitResources:
  used:
  - alias: loadbalancer:modiaeventdistribution
    resourceType: loadbalancerconfig
  - alias: events-api
    resourceType: restservice
  exposed:
  - alias: modiaeventdistribution-isalive
    resourceType: restservice
    path: /modiaeventdistribution/internal/isAlive
  - alias: modiaeventdistribution-websocket
    resourceType: restservice
    path: /modiaeventdistribution/websocket
