apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiaeventdistribution
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/isReady
    initialDelay: 20
    timeout: 1
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 60
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 600m
      memory: 512Mi
  redis:
    - instance: contextholder
      access: read
  ingresses:
    - https://modiaeventdistribution.intern.dev.nav.no
    - https://modiaeventdistribution.ansatt.dev.nav.no
  envFrom:
    - secret: modiacontextholder-redis-passord
  env:
    - name: APP_NAME
      value: "modiaeventdistribution"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: BASE_PATH
      value: ""
    - name: APP_ENVIRONMENT
      value: q2
    - name: REDIS_URI
      value: "$(REDIS_URI_CONTEXTHOLDER)"
    - name: REDIS_USER
      value: "$(REDIS_USERNAME_CONTEXTHOLDER)"
    - name: REDIS_PASSWORD
      value: "$(REDIS_PASSWORD_CONTEXTHOLDER)"
